### ISSUE TITLE
Фильтр по дате для списка ГД

### ISSUE THREAD

**Issue by Lelya** [butschster/kodicms#324]
Как в виджете Список ГД добавить фильтр по дате? Например, фитрация по годам для раздела

**Comment by butschster** [comment]
![mysql_function](https://cloud.githubusercontent.com/assets/773481/5740317/506a7c4c-9c13-11e4-8951-636d850c6463.jpg)

Для использования MYSQL функции в фильтрах списка ГД документов используется дополнительное поле в фильтре для указания дополнительных параметров. Данные в это поле вводятся в виде query_string

Функция вводится в виде `MYSQL_FUNCTION_NAME(:field, other_data)`, например 

`db_function=YEAR(:field)`
`db_function=DATE_FORMAT(:field, '%Y')`
