### ISSUE TITLE
Проблема с отображением пункта "Разделы" у ограниченного ролью пользователя

### ISSUE THREAD

**Issue by rizhenkov** [butschster/kodicms#333]
Шаг 1. Мы создали раздел ГД (например, Новости) и поставили галочку "Отображать раздел в корне меню"
Шаг 2. Создали учётку с ролью editor. Дали editor-у право "видеть рабочий стол" и управлять документами ГД "Новости". 
Результат. 
![](http://i.imgur.com/xdxEdI0.png)
Новости отобразились, как надо. Но зачем-то показывается пустой пункт "Разделы" в левом меню, который нельзя развернуть. 

В качестве решения, предлагаю в логическом блоке, который "решает", отображать ли пункт "Разделы", чтобы он не просто считал количество доступных разделов, а проверял, не перечислены ли уже эти разделы ГД в боковом меню.

**Comment by rizhenkov** [comment]
Ну и в догонку. Хотелось бы иметь возможность ограничить доступ к пунктам: документация и система. А то сейчас их нельзя скрыть без правки кода.

**Comment by butschster** [comment]
Если документация не нужна, ее можно отключить в плагинах

**Comment by rizhenkov** [comment]
Документация может быть нужна разработчику или администратору. Но нет возможности закрыть доступ к ней контент-менеджеру (который всё-равно в ней ничего не поймёт).

**Comment by rizhenkov** [comment]
Подтверждаю исправление. Теперь пустые разделы исчезли! Большое спасибо
