### ISSUE TITLE
Проблема с отображением некоторых ошибок

### ISSUE THREAD

**Issue by rizhenkov** [butschster/kodicms#334]
Обратите внимание на сам текст ошибок:
![](http://i.imgur.com/XSzC2hx.png)

![](http://i.imgur.com/g0Fnbmi.png)

**Comment by YouSysAdmin** [comment]
Какой файл вообще отвечает за вывод ошибок, например той-же 403?
Например вижу: 
[/cms/modules/kodicms/views/system/error/default.php](https://github.com/butschster/kodicms/blob/1453e93c41db880a9e34da4175b1b0989d8c4227/cms/modules/kodicms/views/system/error/default.php)
и
[/cms/modules/kodicms/views/system/error/kohana.php](https://github.com/butschster/kodicms/blob/1453e93c41db880a9e34da4175b1b0989d8c4227/cms/modules/kodicms/views/system/error/kohana.php)

В default.php мне кажется стоит привести вывод сообщения к тому-же виду что и в kohana.php

``` php
<?php echo htmlspecialchars( (string) $message, ENT_QUOTES, Kohana::$charset, TRUE); ?>
```

С колокольни безопасности так правильнее :coffee: 
Если ошибся файлами, извиняюсь. Кохану не изучал, поверхностно знаю.

**Comment by butschster** [comment]
@riartem а какой это браузер?

**Comment by rizhenkov** [comment]
Chrome последний, вроде.
![](http://i.imgur.com/bEq2DDu.png)

**Comment by butschster** [comment]
Очень странное поведение, т.к. в моем случае вывод совершенно нормальный, надо будет подумать в чем разница.
![](https://leto45d.storage.yandex.net/rdisk/d8f581a666b7e0850578c2fbe4e236b0/mpfs/tAMn56enYENepycfJvHFDfdqtvDl8_lom_brGH5DiVMIiB1xegogR5_kV8XxPpWyrCpBbh5dDhroi8YDvSLYxw==?uid=0&filename=2015-02-03%2019-15-49%20Untitled-1%20%40%2080%2C9%25%20%28Layer%201%2C%20RGB%208%29%20%20.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&rtoken=a94c2b4ec5c01386b58c806c7e588cd4&force_default=no)

**Comment by rizhenkov** [comment]
Думаю, тут не в браузере дело. Посмотри второй скрин с обычной ошибкой. 
Там ведь безо всяких JS надпись генерируется на бэкенде.

**Comment by YouSysAdmin** [comment]
@riartem Вот @butschster пофиксил немного. Попробуйте обновится или или руками исправить то о чём Я писал выше. 0c4a16f

У меня к сожалению сейчас нет свободных мощностей для развёртывания и тестинга.

**Comment by rizhenkov** [comment]
Готово. Всё исправилось, затестил. Спасибо

**Comment by YouSysAdmin** [comment]
Отличненько.
Спасибо за проверку.
