### ISSUE TITLE
Ошибка при сохранении страницы блога и при обновлении поля

### ISSUE THREAD

**Issue by kudesa** [butschster/kodicms#336]
Создавал блог по видео http://www.youtube.com/watch?v=2aXglNrr9bM
Сохранение страницы блога
![image](https://cloud.githubusercontent.com/assets/1862552/6096665/aa5f07ea-afaf-11e4-96fb-59af25491867.png)

Обновление поля 
![image](https://cloud.githubusercontent.com/assets/1862552/6096658/23a05d9e-afaf-11e4-9187-70b9f023eb1b.png)

Версия kodicms последняя с ветки dev

**Comment by butschster** [comment]
Какая версия PHP?

**Comment by kudesa** [comment]
5.3.29  mamp стандартный

**Comment by butschster** [comment]
Попробуй теперь сохранить документ блога, вроде должно помочь. Если все ок, закрывай тикет

**Comment by kudesa** [comment]
ошибка пропала, сохранение работает, поля изменяются

**Comment by kudesa** [comment]
Снова возникает ошибка при редактировании в виджете поля гибридных данных.
404 во всплывающем окне
![image](https://cloud.githubusercontent.com/assets/1862552/6112021/3a1241ce-b09e-11e4-8d6b-663c26a05146.png)

**Comment by butschster** [comment]
Просьба указать подробнее последовательность действий, которая приводит к данной ошибке

**Comment by kudesa** [comment]
Захожу в виджет blog item, созданный по видео. Раздел «поля документа», кликаю для редактирования по любому полю, открывается всплывающее окно, в нем ошибка 404 .

**Comment by butschster** [comment]
там у каждого поля есть ссылка, сможешь показать ее, возможно она не верно генерируется и установка системы была в корень сервера или в папку?

**Comment by kudesa** [comment]
Установка в корень. 
Ссылка /backend/hybrid/field/edit/1

**Comment by kudesa** [comment]
![image](https://cloud.githubusercontent.com/assets/1862552/6112686/0b320ccc-b0a3-11e4-8000-49794fa65878.png)
ошибка в консоли

**Comment by butschster** [comment]
Если я правильно понимаю, то у тебя ссылка на админ панель не `backend`, а там была жестко забита ссылка на редактирование поля.

**Comment by kudesa** [comment]
да, я сменил на  admin

**Comment by butschster** [comment]
Проверяй, если все ок, закрывай

**Comment by kudesa** [comment]
Заработало, благодарю.
Но в консоли осталась ошибка  dropzone Error: Invalid dropzone element

**Comment by butschster** [comment]
@kudesa, проблемы с Dropbox исправил
