### ISSUE TITLE
Баг redactor. Плодятся слеши в тексте перед кавычками

### ISSUE THREAD

**Issue by kudesa** [butschster/kodicms#337]
После каждого сохранения количество слешей увеличивается 
![image](https://cloud.githubusercontent.com/assets/1862552/6097792/3fdc41ae-afdb-11e4-9daf-ce9829f4cb1e.png)

Также загруженную картинку через  elfinder повредил. (выше скрин)

**Comment by butschster** [comment]
magic_quotes включены?

**Comment by kudesa** [comment]
Включены magic_quotes_gpc

**Comment by butschster** [comment]
необходимо выключить

**Comment by kudesa** [comment]
Ок, благодарю
