### ISSUE TITLE
Синтаксическая ошибка в коде

### ISSUE THREAD

**Issue by ih8ch** [butschster/kodicms#353]
в файле cms/modules/installer/views/install/env_test.php в строке 58 не </tbdoy> а </tbody>.
Прозьба не гневаться, просто хочу хоть чем-то помочь сделать систему идеальной =).

**Comment by butschster** [comment]
Привет, поддержка этой версии прекращена. Сейчас актуальна версия https://github.com/KodiCMS/kodicms-laravel
