### ISSUE TITLE
Invalid value of $PUBLICPATH when outside of CMS

### ISSUE THREAD

**Issue by gestern** [butschster/kodicms#356]
According to `bootstrap.php`:

```
define('PUBLICPATH',            DOCROOT . 'public' . DIRECTORY_SEPARATOR);
```

`$PUBLICPATH` should be `/public/`, but it is not working as supposed when I tried to invoke inside of my layout: `/`. Code:

```
echo Meta::factory($page)
                ->js('jquery', $PUBLICPATH.'js/jquery-latest.min.js');
```

Is there any chance to get right value of `/public` folder through `$<something>`?

**Comment by butschster** [comment]
Correct `PUBLICPATH`, without `$`
`echo Meta::factory($page)->js('jquery', PUBLICPATH.'js/jquery-latest.min.js');`

**Comment by gestern** [comment]
Thanks @butschster, right now `PUBLICPATH` contains absolute path on a web server, like `/var/www/.../public/` but it doesn't have to be, I'd like to get `/public/`. Is it possible?

**Comment by butschster** [comment]
`BASE_URL . 'public/'`
You can create new plugin, create file `init.php` and there place code like this https://github.com/KodiCMS-Kohana/demo-site/blob/master/init.php#L4

```
define('PUBLIC_URL', BASE_URL . 'public/');
```

**Comment by gestern** [comment]
Thank you for your support.
