### ISSUE TITLE
How to render a snippet inside of layout?

### ISSUE THREAD

**Issue by gestern** [butschster/kodicms#357]
I'm want to render a snippet inside of layout. How to do that?

_My steps to reproduce_:
- Create new snippet, for instance: called `take-care` with some html `<h1>Hello World</h1>`;
- Create new `HTML` widget with name `Take-Care`;
- Create new layout to be able to use all above `<?php Block::run('take-care'); ?>`
- Have to change a layout from current to `take-care` in "Page Options" to be able to test new things;
- Refresh just changed page.

So, I had hoped to see my text ("Hello World!"), but I do not see anything. What is wrong?

**Comment by gestern** [comment]
The problem is gone when I'm attended "Widget location" in Widget, I've selected my snippet in "Layout block" and tapped "Rebuild block". Hmm

**Comment by butschster** [comment]
When you create new layout, you can go to `Design -> Layouts` and click "Rebuild blocks" button.

You can also place snippet to layout with code

```
Snippet::render('snippet-name');
```

https://github.com/KodiCMS-Kohana/cms/wiki/Snippets#snippetrender

**Comment by gestern** [comment]
Got it.
